version: '3'
services:
  crud:
    build: .
    ports:
     - "5000:5000"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
